# A basic workflow for Go
name: test-go
on: [push]
defaults:
  run:
    shell: bash -ieo pipefail {0}
    working-directory: go
jobs:
  test:
    name: golang test & build
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.5' # The Go version to download (if necessary) and use.
      - name: test
        run: go test ./...
      - name: build
        run: go build ./cmd/...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29

          # Optional: working directory, useful for monorepos
          working-directory: go
          # These options work around the errors in this issue
          # https://github.com/golangci/golangci-lint-action/issues/244
          skip-pkg-cache: true
          skip-build-cache: true