# A basic workflow for Go
name: test-go
on: [push]
defaults:
  run:
    shell: bash -ieo pipefail {0}
    working-directory: go
jobs:
  test:
    name: python test & build
    runs-on: [ubuntu-20.04]
    container: gcr.io/tensorflow-federated/remote-executor-service:0.32.0@sha256:82aa0520bc2ac4dea31eae486f26780f7220d8dcb2170c4333670fc1dd407b33
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: python version